# Site settings
name: dummer boy
description: "Drummer has the divine rights to rent control"

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://drummerrentcontrol.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: :title/

pagination: true
paginate: 8
paginate_path: page/:num/

author:
    name: "dummer boy"
    email: ""
    uri: "https://drummerrentcontrol.com"

sass:
    sass_dir: _sass
    style: compressed

defaults:
    - scope:
          path: "_posts"
          type: "posts"
      values:
          reading_time: true
          # Meta
          show_tags: true
          show_categories: true
          # Social
          share_buttons: true
          disqus: true

plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap
